### ISSUE TITLE
Attack Bonus doesn't get applied

### ISSUE THREAD

**Issue by ChiefEinherjar** [elizeuangelo/fvtt-beyond-the-wall#2]
Just as the title says.

When a character at level 2 (with a base attack bonus of +2) makes a normal attack the bonus has to be applied manually instead of automatically. When the player doesn't add the +2 every time in the "modifier"-prompt it doesn't get applied.
Especially in the heat of combat this gets overlooked really fast - and is frustrating for the players as well as me (the DM).

**Comment by elizeuangelo** [comment]
I did some changes in the system in the last commit (fe5796eccfc1b39035ebcd77620f3a731130a415), you can now pass character data parameters in the weapon bonus.

`@melee` is now the default value and you can use `@ranged` or any `@system.PARAMETER` you want.

Example:
A weapon bonus `@melee` will apply the characters melee attack bonus to the roll, on top of the modifier.

**Comment by ChiefEinherjar** [comment]
Thanks! Now it works just as expected! And thanks for replying that fast!
